import { Part } from './api';

export interface ProductSubsystem {
  id: string;
  name: string;
  alloy: string;
  tolerance: string;
  layer: string;
}

export interface DetailedProductMeta {
  partId: string;
  productName: string;
  partNumber: string;
  batchId: string;
  metallurgyAlloy: string;
  alloyStandard: string;
  heatTreatment: string;
  toleranceRating: string;
  manufactureDate: string;
  manufacturePlant: string;
  cageCode: string;
  warrantyUntil: string;
  warrantyStatus: string;
  warrantyDaysRemaining: number;
  warrantySLA: string;
  operatingHours: number;
  ratedLifeHours: number;
  operatingDutyCycles: number;
  maxDutyCycles: number;
  operatingTempMin: number;
  operatingTempMax: number;
  operatingTempLabel: string;
  operatingPressureMpa: number;
  vibrationToleranceG: number;
  installedMachine: string;
  installedPosition: string;
  ndtUltrasonic: string;
  ndtXray: string;
  ndtCMM: string;
  nextInspectionDue: string;
  pufHardwareId: string;
  standards: string;
  subsystems: ProductSubsystem[];
}

export const PRODUCT_CATALOG: Record<string, DetailedProductMeta> = {
  'HP47291': {
    partId: 'HP47291',
    productName: 'High-Pressure Hydrogen Fuel Cell Injector Assembly',
    partNumber: 'PN-AERO-47291-B',
    batchId: 'BATCH-AERO-2024-Q3',
    metallurgyAlloy: 'Inconel 718 Superalloy + Platinum-Iridium Nozzle',
    alloyStandard: 'AMS 5596 / ASTM B637',
    heatTreatment: 'Vacuum Solution Annealed at 980°C + Double Precipitation Aged',
    toleranceRating: '±0.001mm',
    manufactureDate: '12-SEP-2024 // 08:30 UTC',
    manufacturePlant: 'Apex Aerospace Technologies (Plant 02, Munich)',
    cageCode: 'CAGE: C4921 / NSN: 2915-01-682-9901',
    warrantyUntil: '15-NOV-2027',
    warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
    warrantyDaysRemaining: 777,
    warrantySLA: 'Tier-1 High-Pressure Fuel System Guarantee',
    operatingHours: 3450,
    ratedLifeHours: 12000,
    operatingDutyCycles: 980,
    maxDutyCycles: 4500,
    operatingTempMin: -253,
    operatingTempMax: 950,
    operatingTempLabel: '-253°C Cryo LH2 to +950°C Combustor',
    operatingPressureMpa: 350,
    vibrationToleranceG: 35,
    installedMachine: 'Boeing EcoDemonstrator Testbed #09 (Port Thruster)',
    installedPosition: 'Port Nacelle Engine Bay // Station 4B Injection Ring',
    ndtUltrasonic: 'Zero Voids / Ra 0.08 Laser Micro-Bore Verified',
    ndtXray: 'High-Flux Synchrotron Computed Tomography Passed',
    ndtCMM: '±0.0008 mm Geometric True Position Validated',
    nextInspectionDue: '15-OCT-2026',
    pufHardwareId: '#PUF-718-H2-INJECTOR-91',
    standards: 'FAA 8130-3 / EASA Form 1 / AS9100D Rev D',
    subsystems: [
      { id: 'casing', name: 'External Cryo-Insulation Jacket', alloy: 'Inconel 718 Superalloy', tolerance: '±0.003mm', layer: 'Outer Vacuum Barrier' },
      { id: 'manifold', name: 'Micro-Channel Fuel Distribution Rail', alloy: 'Haynes 282 High-Temp Alloy', tolerance: '±0.001mm', layer: 'Fuel Metering Core' },
      { id: 'rotor', name: 'Swirl Atomization Micro-Nozzle', alloy: 'Platinum-Iridium Pt90-Ir10', tolerance: '±0.0005mm', layer: '350-Bar Sonic Jet Ring' },
      { id: 'bearings', name: 'Self-Lubricating Cryo Bushing', alloy: 'Torlon 4203 Polyamide-Imide', tolerance: '±0.0005mm', layer: 'LH2 Cryo Seal Race' },
      { id: 'sensor', name: 'Optoelectronic Pressure Transceiver', alloy: 'Fused Silica Fiber Bragg Grating', tolerance: '±0.0005mm', layer: 'Realtime Bus Sensor' },
    ],
  },

  'QC-CRYOPUMP-88': {
    partId: 'QC-CRYOPUMP-88',
    productName: 'Superconducting Helium-3 Dilution Refrigerator Pulse-Tube Core',
    partNumber: 'PN-QC-8820-ULTRA',
    batchId: 'BATCH-QUANTUM-2025-01',
    metallurgyAlloy: 'High-Purity OFHC Copper (99.99%) + Titanium Grade 2',
    alloyStandard: 'ASTM B170 (C10100) / ASTM B348',
    heatTreatment: 'Ultra-High Vacuum Degassed at 650°C / Hydrogen Annealed',
    toleranceRating: '±0.0005mm',
    manufactureDate: '08-JAN-2025 // 11:20 UTC',
    manufacturePlant: 'Titanium Precision Micro-Forging (Bavaria)',
    cageCode: 'CAGE: T8812 / NSN: 4110-01-711-2044',
    warrantyUntil: '30-JUN-2028',
    warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
    warrantyDaysRemaining: 1005,
    warrantySLA: 'Millikelvin Thermal Vacuum SLA',
    operatingHours: 1240,
    ratedLifeHours: 20000,
    operatingDutyCycles: 140,
    maxDutyCycles: 1200,
    operatingTempMin: -273.135,
    operatingTempMax: 30,
    operatingTempLabel: '0.015 Kelvin (-273.135°C) Deep Cryo',
    operatingPressureMpa: 45,
    vibrationToleranceG: 12,
    installedMachine: 'Rigetti Quantum Supercluster Node 7 (0.015K Dilution Core)',
    installedPosition: 'Cryostat Vacuum Stage 4 // Sub-Millikelvin Mixing Chamber',
    ndtUltrasonic: 'Zero Micro-Inclusions / Ra 0.05 Superconducting Polish',
    ndtXray: 'Helium Leak Rate < 10^-11 mbar*L/s Verified',
    ndtCMM: '±0.0003 mm Sphericity / Regenerator Matrix Cleared',
    nextInspectionDue: '10-JAN-2027',
    pufHardwareId: '#PUF-QC-COPPER-CORE-88',
    standards: 'ISO 9001:2015 / NIST SP 800-162 Compliant',
    subsystems: [
      { id: 'casing', name: '4-Kelvin Cryostat Radiation Shield', alloy: 'OFHC Ultra-Pure Copper C10100', tolerance: '±0.002mm', layer: 'Superconducting Enclosure' },
      { id: 'manifold', name: 'He-3 Regenerator Matrix Block', alloy: 'Sintered Spherical Bronze Mesh', tolerance: '±0.001mm', layer: 'Phase Boundary Core' },
      { id: 'rotor', name: 'Acoustic Resonator Waveguide', alloy: 'Titanium Grade 2 Non-Magnetic', tolerance: '±0.0008mm', layer: 'Pulse-Tube Acoustic Column' },
      { id: 'bearings', name: 'Passive Magnetic Levitation Damper', alloy: 'SmCo Permanent Rare-Earth Magnet', tolerance: '±0.0002mm', layer: 'Zero-Vibration Float' },
      { id: 'sensor', name: 'Dual SQUID Flux Quantum Magnetometer', alloy: 'Niobium-Aluminum Oxide (Nb/AlOx)', tolerance: '±0.0001mm', layer: 'Millikelvin Telemetry' },
    ],
  },

  'TITAN-TURBINE-X1': {
    partId: 'TITAN-TURBINE-X1',
    productName: 'Single-Crystal Titanium-Aluminide Ceramic Matrix Turbine Blade Array',
    partNumber: 'PN-RB-TURB-9011',
    batchId: 'BATCH-ROLLS-SX9-04',
    metallurgyAlloy: 'Single-Crystal CMSX-4 Monocrystal Nickel-Superalloy',
    alloyStandard: 'AMS 5873 / AS9100D Certified',
    heatTreatment: 'Homogenized at 1,315°C / 4-Stage Argon Quenched + Diffusion Coated',
    toleranceRating: '±0.0008mm',
    manufactureDate: '14-MAR-2024 // 08:30 UTC',
    manufacturePlant: 'Titanium Precision Micro-Forging (Bavaria)',
    cageCode: 'CAGE: C4921 / NSN: 2840-01-529-8812',
    warrantyUntil: '20-AUG-2027',
    warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
    warrantyDaysRemaining: 690,
    warrantySLA: 'Commercial High-Bypass Flight Hour Power-By-The-Hour',
    operatingHours: 5120,
    ratedLifeHours: 18000,
    operatingDutyCycles: 1420,
    maxDutyCycles: 6000,
    operatingTempMin: -65,
    operatingTempMax: 1650,
    operatingTempLabel: '-65°C to +1,650°C Gas Combustion Stream',
    operatingPressureMpa: 850,
    vibrationToleranceG: 60,
    installedMachine: 'Rolls-Royce Trent 1000 High-Bypass Turbofan SN-4819',
    installedPosition: 'Stage 1 High-Pressure Turbine Rotor (Disk 01, Blade #24)',
    ndtUltrasonic: 'Zero Voids / Ra 0.18 Sub-Surface Integrity Confirmed',
    ndtXray: '100% Volumetric Computed Tomography Class A1 Cleared',
    ndtCMM: '±0.0008 mm Aerofoil Contour Validated',
    nextInspectionDue: '18-APR-2027',
    pufHardwareId: '#PUF-CMSX4-SX9-TURBINE-01',
    standards: 'FAA 8130-3 / EASA Form 1 / AS9100D Rev D',
    subsystems: [
      { id: 'casing', name: 'External Abrasive Shroud Ring', alloy: 'Forged Waspaloy Heat-Treated', tolerance: '±0.005mm', layer: 'Blade Tip Clearance Seal' },
      { id: 'manifold', name: 'Internal Cooling Air Plenum Vane', alloy: 'Mar-M-247 Directionally Solidified', tolerance: '±0.002mm', layer: 'Convective Film Cooling' },
      { id: 'rotor', name: 'Single-Crystal Aerofoil Core', alloy: 'CMSX-4 Monocrystal Alloy', tolerance: '±0.0008mm', layer: '15,000 RPM Rotational Root' },
      { id: 'bearings', name: 'Silicon Nitride (Si3N4) Hybrid Race', alloy: 'Hot Isostatic Pressed Si3N4 Ceramic', tolerance: '±0.0004mm', layer: 'High-Speed Ceramic Spool' },
      { id: 'sensor', name: 'Sapphire Optical Pyrometer Probe', alloy: 'Monocrystalline Al2O3 Sapphire', tolerance: '±0.0005mm', layer: '1,700°C IR Blade Telemetry' },
    ],
  },

  'LIDAR-PHOENIX-4D': {
    partId: 'LIDAR-PHOENIX-4D',
    productName: '1550nm Solid-State 4D Matrix FMCW LiDAR Transceiver',
    partNumber: 'PN-LID-4D-990',
    batchId: 'BATCH-APEX-LID-88',
    metallurgyAlloy: '6061-T6 Billet Aluminum + Optical Fused Silica',
    alloyStandard: 'AMS 4027 / MIL-STD-810H',
    heatTreatment: 'T6 Solution Heat Treated and Artificially Aged (Hardness 95 HB)',
    toleranceRating: '±0.002mm',
    manufactureDate: '05-OCT-2024 // 16:45 UTC',
    manufacturePlant: 'Apex Aerospace Technologies (Plant 01, Berlin)',
    cageCode: 'CAGE: L9901 / NSN: 5840-01-692-1088',
    warrantyUntil: '31-DEC-2026',
    warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
    warrantyDaysRemaining: 458,
    warrantySLA: 'Autonomous Mining & Extreme Duty Environmental SLA',
    operatingHours: 6800,
    ratedLifeHours: 25000,
    operatingDutyCycles: 2840,
    maxDutyCycles: 15000,
    operatingTempMin: -45,
    operatingTempMax: 105,
    operatingTempLabel: '-45°C Arctic to +105°C Mining Ambient',
    operatingPressureMpa: 12,
    vibrationToleranceG: 45,
    installedMachine: 'Volvo Autonomous Heavy Hauler Truck #104 (Autonomous Mining)',
    installedPosition: 'Front Bumper Cab Array // Port 4D FMCW Sensor Pod',
    ndtUltrasonic: 'IP69K Immersion Sealing Cleared / Zero Internal Voids',
    ndtXray: 'Optical Alignment Interferometry Passed',
    ndtCMM: '±0.0015 mm Mechanical Datum Points Verified',
    nextInspectionDue: '15-NOV-2026',
    pufHardwareId: '#PUF-LIDAR-1550-PHOENIX-4D',
    standards: 'ISO 26262 ASIL-D / MIL-STD-810H Level 4',
    subsystems: [
      { id: 'casing', name: 'Cast Hermetic Enclosure', alloy: 'Die-Cast A380 Aluminum Alloy', tolerance: '±0.010mm', layer: 'IP69K Impact Armor' },
      { id: 'manifold', name: 'Optical Bench Chassis Platform', alloy: 'Invar 36 Near-Zero CTE Alloy', tolerance: '±0.001mm', layer: 'Athermal Optical Bench' },
      { id: 'rotor', name: 'Resonant MEMS Beam Steering Matrix', alloy: 'Monocrystalline Silicon (Si-100)', tolerance: '±0.0002mm', layer: '20kHz 2D Scanning Mirror' },
      { id: 'bearings', name: 'Torsional Flexure Suspension', alloy: 'Beryllium-Copper Alloy 172 (C17200)', tolerance: '±0.0005mm', layer: 'Stiction-Free Flexure Pivot' },
      { id: 'sensor', name: 'Heterodyne Photodiode Coherent RX', alloy: 'InGaAs Photodiode on InP Substrate', tolerance: '±0.0005mm', layer: '1550nm Laser Receiver' },
    ],
  },

  'HYDRO-ACT-9900': {
    partId: 'HYDRO-ACT-9900',
    productName: 'Supercritical 450-Bar Electro-Hydraulic Thrust Vector Actuator',
    partNumber: 'PN-HYD-ACT-9900',
    batchId: 'BATCH-REXROTH-HYD-12',
    metallurgyAlloy: 'Maraging Steel Grade 300 (Vascomax 300) / CuBe2 Bronze',
    alloyStandard: 'AMS 6514 / MIL-S-46850',
    heatTreatment: 'Vacuum Solution Annealed 820°C + Aged at 480°C (Tensile 2,050 MPa)',
    toleranceRating: '±0.0005mm',
    manufactureDate: '22-JUN-2024 // 07:15 UTC',
    manufacturePlant: 'Titanium Precision Micro-Forging (Bavaria)',
    cageCode: 'CAGE: H9900 / NSN: 1650-14-550-4821',
    warrantyUntil: '10-APR-2027',
    warrantyStatus: 'FLAGGED // UNDER AI ORACLE REVIEW',
    warrantyDaysRemaining: 558,
    warrantySLA: 'Launch Vehicle Mission-Critical Single-Stage Escrow',
    operatingHours: 820,
    ratedLifeHours: 8000,
    operatingDutyCycles: 310,
    maxDutyCycles: 2500,
    operatingTempMin: -50,
    operatingTempMax: 260,
    operatingTempLabel: '-50°C Stratospheric to +260°C Rocket Plume',
    operatingPressureMpa: 450,
    vibrationToleranceG: 75,
    installedMachine: 'Ariane 6 Rocket Gimbal Stage 1 (Main Actuator Bay 2)',
    installedPosition: 'Stage 1 Vulcain 2.1 Engine Gimbal Gimbal Axis Beta',
    ndtUltrasonic: 'Class AA Immersion Pulse-Echo Passed (Ra 0.05)',
    ndtXray: 'Radiographic Weld Seam 100% Defect Free',
    ndtCMM: '±0.0005 mm Hydraulic Bore Concentricity Cleared',
    nextInspectionDue: '15-DEC-2026',
    pufHardwareId: '#PUF-MARAGING-HYD-ACT-9900',
    standards: 'ESA ECSS-E-ST-32C / AS9100D Rev D',
    subsystems: [
      { id: 'casing', name: 'Supercritical Pressure Cylinder Barrel', alloy: 'Vascomax 300 Maraging Steel', tolerance: '±0.002mm', layer: '450-Bar Hydrostatic Cylinder' },
      { id: 'manifold', name: 'Dual-Redundant Spool Valve Block', alloy: '15-5 PH Stainless Steel (AMS 5659)', tolerance: '±0.001mm', layer: 'Dual Servo Hydraulic Manifold' },
      { id: 'rotor', name: 'Hydraulic Piston Actuator Ram', alloy: 'Nitrided Maraging 300 (Ra 0.04)', tolerance: '±0.0008mm', layer: 'Hard Chrome Coated Ram' },
      { id: 'bearings', name: 'Self-Aligning Gimbal Spherical Rod', alloy: 'Stellite 6 Hardfacing Alloy', tolerance: '±0.0005mm', layer: 'Gimbal Swivel Joint' },
      { id: 'sensor', name: 'Dual LVDT Linear Stroke Transceiver', alloy: 'Permalloy 80 Shielded Housing', tolerance: '±0.0005mm', layer: 'Sub-Micron Stroke Sensor' },
    ],
  },

  'SIC-INVERTER-800V': {
    partId: 'SIC-INVERTER-800V',
    productName: '800V High-Bandgap Silicon-Carbide Dual Traction Inverter',
    partNumber: 'PN-SIC-800-REV4',
    batchId: 'BATCH-POWERTRAIN-2024-C',
    metallurgyAlloy: 'AlSiC Metal Matrix Composite + Direct Bonded Copper (DBC)',
    alloyStandard: 'ISO 26262 ASIL-D / AEC-Q101',
    heatTreatment: 'Vacuum Sintered AlSiC Baseplate / High-Reliability Laser Welded',
    toleranceRating: '±0.001mm',
    manufactureDate: '19-FEB-2024 // 14:00 UTC',
    manufacturePlant: 'Gigafactory Fab-09 Advanced Robotics (Stuttgart)',
    cageCode: 'CAGE: S8000 / NSN: 6130-12-398-1090',
    warrantyUntil: '18-MAY-2026',
    warrantyStatus: 'CLAIM PENDING // SENSORS OVER-CURRENT',
    warrantyDaysRemaining: 231,
    warrantySLA: 'OEM High-Performance Electric Powertrain Indemnity',
    operatingHours: 4100,
    ratedLifeHours: 30000,
    operatingDutyCycles: 6800,
    maxDutyCycles: 50000,
    operatingTempMin: -40,
    operatingTempMax: 175,
    operatingTempLabel: '-40°C Winter to +175°C SiC Junction Temp',
    operatingPressureMpa: 8,
    vibrationToleranceG: 25,
    installedMachine: 'Porsche GT4 e-Performance Prototype Chassis #088',
    installedPosition: 'Rear Electric Axle Inverter Enclosure (Module A)',
    ndtUltrasonic: 'Acoustic Scanning Microscopy (SAM) Zero Delamination',
    ndtXray: 'Die Attach Solder Voids < 2.5% Cleared',
    ndtCMM: '±0.0010 mm Busbar Flatness Validated',
    nextInspectionDue: '30-AUG-2026',
    pufHardwareId: '#PUF-SIC-800V-INVERTER-412',
    standards: 'ISO 26262 ASIL-D / ISO 16750 Environmental',
    subsystems: [
      { id: 'casing', name: 'Direct-Liquid Coldplate Enclosure', alloy: 'AlSiC Metal Matrix Composite', tolerance: '±0.005mm', layer: 'Pin-Fin Water Glycol Coldplate' },
      { id: 'manifold', name: 'Low-Inductance DC-Link Busbar', alloy: 'Oxygen-Free Copper C11000 (Plated)', tolerance: '±0.002mm', layer: '<15nH Parasitic Busbar' },
      { id: 'rotor', name: '800V Dual SiC MOSFET Switching Bridge', alloy: 'Bare SiC Die on AlN DBC Substrate', tolerance: '±0.0005mm', layer: '450kW Peak Power Bridge' },
      { id: 'bearings', name: 'High-Isolation Gate Driver Core', alloy: 'PEEK Polymer Insulator (5kV Rated)', tolerance: '±0.001mm', layer: 'Galvanic Isolation Barrier' },
      { id: 'sensor', name: 'Giant Magnetoresistance (GMR) Shunt', alloy: 'GMR Multi-Layer Film on Si', tolerance: '±0.0005mm', layer: 'Microsecond Current Telemetry' },
    ],
  },

  'CERAMIC-ROTOR-Z': {
    partId: 'CERAMIC-ROTOR-Z',
    productName: 'Carbon-Silicon-Carbide Ventilated 3D-Matrix Brake Rotor',
    partNumber: 'PN-BRM-CCM-420',
    batchId: 'BATCH-BREMBO-CARB-01',
    metallurgyAlloy: 'C/C-SiC Carbon-Ceramic Matrix / Ergal 7075-T6 Bell',
    alloyStandard: 'FIA LMH Technical Regulations / AS9100D',
    heatTreatment: 'Pyrolyzed at 1,000°C + Liquid Silicon Infiltrated at 1,600°C',
    toleranceRating: '±0.0005mm',
    manufactureDate: '28-MAR-2023 // 10:30 UTC',
    manufacturePlant: 'Hexcel Advanced Composites & Nano (Zurich)',
    cageCode: 'CAGE: F5100 / NSN: 2530-15-882-9011',
    warrantyUntil: '15-JUN-2025',
    warrantyStatus: 'RETIRED // LIFECYCLE COMPLETED',
    warrantyDaysRemaining: 0,
    warrantySLA: 'Endurance Racing 24h Le Mans Operational SLA',
    operatingHours: 9800,
    ratedLifeHours: 12000,
    operatingDutyCycles: 4500,
    maxDutyCycles: 6000,
    operatingTempMin: 20,
    operatingTempMax: 1400,
    operatingTempLabel: '+20°C Ambient to +1,400°C Friction Peak',
    operatingPressureMpa: 180,
    vibrationToleranceG: 50,
    installedMachine: 'Ferrari 499P Le Mans Hypercar #51 (Front Axle Left)',
    installedPosition: 'Front Axle Hub // Upright Left Caliper Spindle',
    ndtUltrasonic: 'Resonant Acoustic Method (RAM) Zero Crack Confirmed',
    ndtXray: 'CT Volumetric Density Uniformity Cleared',
    ndtCMM: '±0.0005 mm Disc Runout / Thickness Variation Validated',
    nextInspectionDue: 'RETIRED',
    pufHardwareId: '#PUF-CSIC-ROTOR-BREMBO-51',
    standards: 'FIA Appendix J / ISO 9001:2015 Precision',
    subsystems: [
      { id: 'casing', name: 'Floating Mounting Bell Hub', alloy: 'Forged Ergal 7075-T6 Hard-Anodized', tolerance: '±0.005mm', layer: 'Lightweight Splined Center Bell' },
      { id: 'manifold', name: 'Aerodynamic Curved Airfoil Vanes', alloy: 'Carbon-Ceramic C/C-SiC Matrix', tolerance: '±0.003mm', layer: 'High-CFM Directional Cooling' },
      { id: 'rotor', name: '3D Carbon-Fiber Friction Ring', alloy: 'Siliconized Carbon-Ceramic Matrix', tolerance: '±0.0008mm', layer: '1,400°C Friction Surface' },
      { id: 'bearings', name: 'Radial Floating Thermal Drive Bushings', alloy: 'Inconel 718 High-Strength Alloy', tolerance: '±0.0005mm', layer: 'Thermal Expansion Float Pins' },
      { id: 'sensor', name: 'Embedded Infrared Temperature Sensor', alloy: 'Platinum RTD Glass-Encapsulated', tolerance: '±0.0005mm', layer: 'Realtime Rotor Temperature Bus' },
    ],
  },

  'OPTICAL-GYRO-NAV': {
    partId: 'OPTICAL-GYRO-NAV',
    productName: 'Tri-Axis Ring Laser Gyroscope Tactical Inertial Navigation System',
    partNumber: 'PN-RLG-NAV-770',
    batchId: 'BATCH-HONEYWELL-RLG-55',
    metallurgyAlloy: 'Zerodur Glass-Ceramic + Invar 36 Near-Zero Expansion',
    alloyStandard: 'MIL-PRF-55310 / ITAR Governed',
    heatTreatment: 'Precision Annealed Zerodur Monolithic Block / Ultra-Stable',
    toleranceRating: '±0.0001mm',
    manufactureDate: '04-JUL-2024 // 12:00 UTC',
    manufacturePlant: 'Apex Aerospace Technologies (Munich)',
    cageCode: 'CAGE: H5500 / NSN: 6615-01-582-9902',
    warrantyUntil: '31-DEC-2029',
    warrantyStatus: 'ACTIVE // FULL SOVEREIGN ESCROW',
    warrantyDaysRemaining: 1189,
    warrantySLA: 'Interplanetary Guidance Mission-Critical Assurance',
    operatingHours: 850,
    ratedLifeHours: 50000,
    operatingDutyCycles: 120,
    maxDutyCycles: 5000,
    operatingTempMin: -55,
    operatingTempMax: 90,
    operatingTempLabel: '-55°C Orbital Deep Space to +90°C Launch Core',
    operatingPressureMpa: 10,
    vibrationToleranceG: 40,
    installedMachine: 'SpaceX Falcon Heavy Stage 2 Interplanetary Guidance Flight Unit',
    installedPosition: 'Interstage Avionics Bay // Primary Inertial Reference Rack',
    ndtUltrasonic: 'Zero Acoustic Internal Defects (Ra 0.02)',
    ndtXray: 'Helium Cavity Leak Rate < 10^-12 mbar*L/s Verified',
    ndtCMM: '±0.0001 mm Laser Cavity True Alignment Cleared',
    nextInspectionDue: '01-OCT-2027',
    pufHardwareId: '#PUF-ZERODUR-RLG-NAV-770',
    standards: 'MIL-STD-810H / NASA-STD-8739 Compliant',
    subsystems: [
      { id: 'casing', name: 'Monolithic Inertial Enclosure', alloy: 'Zerodur Ultra-Low Expansion Ceramic', tolerance: '±0.0002mm', layer: 'Zero-CTE Sealed Gyro Body' },
      { id: 'manifold', name: 'He-Ne Optical Resonator Cavity', alloy: 'Precision Laser-Drilled Optical Path', tolerance: '±0.0001mm', layer: '632.8nm He-Ne Laser Path' },
      { id: 'rotor', name: 'Super-Polished Dielectric Mirror', alloy: 'SiO2-Ta2O5 Multi-Layer 99.999% Reflective', tolerance: '±0.0001mm', layer: 'Optical Ring Laser Cavity' },
      { id: 'bearings', name: 'Piezoelectric Micro-Dither Transducer', alloy: 'Lead Zirconate Titanate (PZT) Ceramic', tolerance: '±0.0002mm', layer: 'Anti-Lock-In Dither Mount' },
      { id: 'sensor', name: 'Heterodyne Photodiode Counter Array', alloy: 'Silicon PIN Photodetector Quad-Cell', tolerance: '±0.0001mm', layer: '0.001 deg/hr Sagnac Telemetry' },
    ],
  },
};

export function getProductMetadata(partId: string, fallbackPart?: Part | null): DetailedProductMeta {
  if (PRODUCT_CATALOG[partId]) {
    return PRODUCT_CATALOG[partId];
  }

  // Derive dynamic realistic specifications from the part object itself
  const pid = fallbackPart?.partId || partId || 'ASSET-PART';
  const isTurbine = pid.includes('TURB') || pid.includes('BLADE') || pid.includes('HPT') || pid.includes('CFM');
  const isValve = pid.includes('VALVE') || pid.includes('ACT') || pid.includes('HYDRO');
  const isBearing = pid.includes('BEARING') || pid.includes('BRG');
  const isElectronics = pid.includes('ECU') || pid.includes('INVERTER') || pid.includes('SIC') || pid.includes('LIDAR') || pid.includes('RADAR') || pid.includes('NAV');

  if (isValve) {
    return {
      partId: pid,
      productName: fallbackPart?.installedMachine ? `${pid} // Cryogenic Valve Actuator` : 'Supercritical Fluid Flow Valve',
      partNumber: fallbackPart?.partNumber || `PN-${pid}-2024`,
      batchId: fallbackPart?.batchId || 'BATCH-VALVE-24',
      metallurgyAlloy: 'Inconel 718 Superalloy (AMS 5596 / ASTM B637)',
      alloyStandard: 'AMS 5596 / AS9100D Certified',
      heatTreatment: 'Solution Annealed at 980°C + Aged at 720°C (Tensile 1,420 MPa)',
      toleranceRating: '±0.0015mm',
      manufactureDate: '18-MAY-2024 // 14:15 UTC',
      manufacturePlant: fallbackPart?.manufacturer?.name || 'Apex Aerospace Technologies',
      cageCode: 'CAGE: C4921 / NSN: 4820-01-612-4401',
      warrantyUntil: fallbackPart?.warrantyUntil ? new Date(fallbackPart.warrantyUntil).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '30-JUN-2028',
      warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
      warrantyDaysRemaining: 730,
      warrantySLA: 'Tier-1 Valve Escrow Replacement Guarantee',
      operatingHours: fallbackPart?._count?.events ? fallbackPart._count.events * 650 : 2450,
      ratedLifeHours: 15000,
      operatingDutyCycles: 620,
      maxDutyCycles: 5000,
      operatingTempMin: -253,
      operatingTempMax: 700,
      operatingTempLabel: '-253°C Cryo to +700°C High-Pressure',
      operatingPressureMpa: 450,
      vibrationToleranceG: 30,
      installedMachine: fallbackPart?.installedMachine || 'Boeing 777-300ER // GE90 Fuel Manifold',
      installedPosition: 'Engine Bay Station 2 // Port Fuel Metering Unit',
      ndtUltrasonic: 'Class AA Immersion Zero Voids (Ra 0.12)',
      ndtXray: '100% Volumetric Computed Tomography Passed',
      ndtCMM: '±0.0010 mm Geometric Tolerance Validated',
      nextInspectionDue: '12-NOV-2027',
      pufHardwareId: `#PUF-VALVE-${pid}`,
      standards: 'FAA 8130-3 / EASA Form 1 / AS9100D Rev D',
      subsystems: [
        { id: 'casing', name: 'Supercritical Valve Enclosure', alloy: 'Inconel 718 Superalloy', tolerance: '±0.002mm', layer: 'Outer Pressure Containment' },
        { id: 'manifold', name: 'Dual-Stage Metering Manifold', alloy: '15-5 PH Stainless Steel', tolerance: '±0.001mm', layer: 'Hydraulic Fuel Metering' },
        { id: 'rotor', name: 'High-Pressure Poppet Valve Core', alloy: 'Stellite 6 Hardfacing Alloy', tolerance: '±0.0005mm', layer: 'Zero-Leakage Sealing Face' },
        { id: 'bearings', name: 'Cryogenic Spool Sleeve', alloy: 'Torlon 4203 Polymer Composite', tolerance: '±0.0005mm', layer: 'Friction-Free Actuation Race' },
        { id: 'sensor', name: 'Fiber Bragg Pressure Transceiver', alloy: 'Fused Silica Optical Waveguide', tolerance: '±0.0005mm', layer: 'Bus Pressure Telemetry' },
      ],
    };
  }

  if (isBearing) {
    return {
      partId: pid,
      productName: `${pid} // Hybrid Ceramic Bearing Assembly`,
      partNumber: fallbackPart?.partNumber || `PN-BRG-${pid}`,
      batchId: fallbackPart?.batchId || 'BATCH-BRG-24',
      metallurgyAlloy: 'Silicon Nitride (Si3N4) Ceramic + Cronidur 30 Steel',
      alloyStandard: 'AMS 5925 / AS9100D Certified',
      heatTreatment: 'Hot Isostatic Pressed (HIP) at 1,750°C / 200 MPa',
      toleranceRating: '±0.0005mm',
      manufactureDate: '09-FEB-2024 // 09:40 UTC',
      manufacturePlant: fallbackPart?.manufacturer?.name || 'Hexcel Advanced Composites',
      cageCode: 'CAGE: H7812 / NSN: 3110-01-499-1022',
      warrantyUntil: fallbackPart?.warrantyUntil ? new Date(fallbackPart.warrantyUntil).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '15-SEP-2027',
      warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
      warrantyDaysRemaining: 534,
      warrantySLA: 'OEM High-Speed Spool Bearing SLA',
      operatingHours: fallbackPart?._count?.events ? fallbackPart._count.events * 850 : 3100,
      ratedLifeHours: 25000,
      operatingDutyCycles: 920,
      maxDutyCycles: 8000,
      operatingTempMin: -60,
      operatingTempMax: 450,
      operatingTempLabel: '-60°C to +450°C High-Speed Spool',
      operatingPressureMpa: 720,
      vibrationToleranceG: 50,
      installedMachine: fallbackPart?.installedMachine || 'Airbus A320neo // LEAP-1B Core',
      installedPosition: 'Engine Centerline // No. 3 Bearing Location',
      ndtUltrasonic: 'Resonant Acoustic Method (RAM) Zero Flaws',
      ndtXray: 'Fluorescent Penetrant Level 4 Cleared',
      ndtCMM: '±0.0005 mm Sphericity / Runout Validated',
      nextInspectionDue: '30-OCT-2026',
      pufHardwareId: `#PUF-BRG-HYBRID-${pid}`,
      standards: 'FAA 8130-3 / EASA Form 1 / AS9100D Rev D',
      subsystems: [
        { id: 'casing', name: 'Cronidur 30 Outer Bearing Ring', alloy: 'Pressurized Nitrogen Cronidur 30', tolerance: '±0.001mm', layer: 'Outer Retention Housing' },
        { id: 'manifold', name: 'Internal Oil Scavenge Jet Nozzle', alloy: 'Titanium Ti-6Al-4V Grade 5', tolerance: '±0.001mm', layer: 'Under-Race Lubrication Port' },
        { id: 'rotor', name: 'Silicon Nitride (Si3N4) Rolling Balls', alloy: 'HIP Sintered Si3N4 Ceramic', tolerance: '±0.0003mm', layer: '25,000 RPM Ceramic Balls' },
        { id: 'bearings', name: 'Silver-Plated PEEK Cage Ring', alloy: 'PEEK Polymer + 10um Pure Silver', tolerance: '±0.0005mm', layer: 'Low-Friction Ball Separator' },
        { id: 'sensor', name: 'Piezoelectric Accelerometer Probe', alloy: 'High-Temperature PZT-5A', tolerance: '±0.0005mm', layer: 'Vibration & Spall Telemetry' },
      ],
    };
  }

  if (isElectronics) {
    return {
      partId: pid,
      productName: `${pid} // Solid-State Sensor & Avionics Core`,
      partNumber: fallbackPart?.partNumber || `PN-ELEC-${pid}`,
      batchId: fallbackPart?.batchId || 'BATCH-AVIONICS-24',
      metallurgyAlloy: 'AlSiC Metal Matrix Composite + Gold-Plated Kovar',
      alloyStandard: 'MIL-PRF-38534 / AS9100D',
      heatTreatment: 'T6 Solution Heat Treated + Hermetically Sealed',
      toleranceRating: '±0.002mm',
      manufactureDate: '11-AUG-2024 // 10:00 UTC',
      manufacturePlant: fallbackPart?.manufacturer?.name || 'Apex Aerospace Technologies',
      cageCode: 'CAGE: A8800 / NSN: 5840-01-692-0044',
      warrantyUntil: fallbackPart?.warrantyUntil ? new Date(fallbackPart.warrantyUntil).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '01-SEP-2028',
      warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
      warrantyDaysRemaining: 702,
      warrantySLA: 'Avionics Flight-Control Triple-Lockstep SLA',
      operatingHours: fallbackPart?._count?.events ? fallbackPart._count.events * 550 : 2150,
      ratedLifeHours: 35000,
      operatingDutyCycles: 1540,
      maxDutyCycles: 20000,
      operatingTempMin: -55,
      operatingTempMax: 125,
      operatingTempLabel: '-55°C High-Altitude to +125°C Junction',
      operatingPressureMpa: 15,
      vibrationToleranceG: 30,
      installedMachine: fallbackPart?.installedMachine || 'Joby Aviation eVTOL Autonomous Air Taxi #03',
      installedPosition: 'Nose Avionics Bay // Primary Flight Computer #1',
      ndtUltrasonic: 'C-SAM Acoustic Microscopy Zero Delamination',
      ndtXray: 'X-Ray BGA Solder Joint 100% Cleared',
      ndtCMM: '±0.0010 mm Module Enclosure Validated',
      nextInspectionDue: '01-AUG-2027',
      pufHardwareId: `#PUF-AVIONICS-${pid}`,
      standards: 'DO-254 DAL-A / DO-178C / AS9100D Rev D',
      subsystems: [
        { id: 'casing', name: 'Avionic EMI Shielded Enclosure', alloy: 'AlSiC Metal Matrix Composite', tolerance: '±0.005mm', layer: '40dB RF Shield Enclosure' },
        { id: 'manifold', name: 'Micro-Channel Vapor Coldplate', alloy: 'Electrolytic Copper C11000', tolerance: '±0.002mm', layer: '2-Phase Heat Spreader' },
        { id: 'rotor', name: 'High-Bandwidth Monolithic Compute Core', alloy: 'Silicon FinFET on Low-k Dielectric', tolerance: '±0.0002mm', layer: 'Multi-Core Processor Die' },
        { id: 'bearings', name: 'Anti-Vibration Shock Isolation Gel', alloy: 'Fluorosilicone Military Elastomer', tolerance: '±0.001mm', layer: '30G Flight Shock Isolation' },
        { id: 'sensor', name: 'Optical Bus Telemetry Transceiver', alloy: 'InGaAs VCSEL Laser Diode', tolerance: '±0.0005mm', layer: 'Gigabit Fiber Telemetry' },
      ],
    };
  }

  // Default: Titanium Turbofan Blade & High-Temp Rotor
  return {
    partId: pid,
    productName: fallbackPart?.installedMachine || `${pid} // Titanium High-Pressure Assembly`,
    partNumber: fallbackPart?.partNumber || `PN-TI-${pid}`,
    batchId: fallbackPart?.batchId || 'BATCH-TI-2024-Q3',
    metallurgyAlloy: 'Titanium Ti-6Al-4V Grade 5 Alpha-Beta Alloy',
    alloyStandard: 'AMS 4911 / ASTM B265 (AS9100D Certified)',
    heatTreatment: 'Vacuum Annealed 730°C for 2h / Rapid Argon Gas Quenched',
    toleranceRating: '±0.001mm',
    manufactureDate: '14-MAR-2024 // 08:30 UTC',
    manufacturePlant: fallbackPart?.manufacturer?.name || 'Apex Aerospace Technologies',
    cageCode: 'CAGE: C4921 / NSN: 2840-01-529-8812',
    warrantyUntil: fallbackPart?.warrantyUntil ? new Date(fallbackPart.warrantyUntil).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '31-DEC-2028',
    warrantyStatus: 'ACTIVE // FULL OEM ESCROW',
    warrantyDaysRemaining: 824,
    warrantySLA: 'Tier-1 High-Pressure Spool Escrow Guarantee',
    operatingHours: fallbackPart?._count?.events ? fallbackPart._count.events * 900 : 4820,
    ratedLifeHours: 20000,
    operatingDutyCycles: 1240,
    maxDutyCycles: 6000,
    operatingTempMin: -65,
    operatingTempMax: 1650,
    operatingTempLabel: '-65°C Continuous to +1,650°C Peak Excursion',
    operatingPressureMpa: 850,
    vibrationToleranceG: 50,
    installedMachine: fallbackPart?.installedMachine || 'Boeing 737-800 // Tail N782AA (Pos #1)',
    installedPosition: 'CFM56 High-Pressure Turbine Stage 1 (Blade Array)',
    ndtUltrasonic: 'Zero Voids / Ra 0.18 Sub-Surface Integrity Confirmed',
    ndtXray: '100% Volumetric Computed Tomography Class A1 Cleared',
    ndtCMM: '±0.0008 mm Aerofoil Contour Validated',
    nextInspectionDue: '18-APR-2027',
    pufHardwareId: `#PUF-TITAN-${pid}`,
    standards: 'FAA 8130-3 / EASA Form 1 / AS9100D Rev D',
    subsystems: [
      { id: 'casing', name: 'External Titanium Shield Cowling', alloy: 'Ti-6Al-4V Grade 5 Alpha-Beta', tolerance: '±0.005mm', layer: 'Outer Aerodynamic Cowling' },
      { id: 'manifold', name: 'High-Pressure Cooling Manifold', alloy: 'Inconel 718 Superalloy', tolerance: '±0.002mm', layer: 'Combustion Pressure Chamber' },
      { id: 'rotor', name: 'Single-Crystal Aerofoil Rotor Core', alloy: 'C/C-SiC Matrix Composite', tolerance: '±0.001mm', layer: '15,000 RPM Rotational Hub' },
      { id: 'bearings', name: 'Ceramic Hybrid Race Assembly', alloy: 'Silicon Nitride (Si3N4) Ceramic', tolerance: '±0.0005mm', layer: 'Low-Friction Bearing Race' },
      { id: 'sensor', name: 'Optical Fiber Bragg Telemetry Core', alloy: 'Fused Silica High-Temp Fiber', tolerance: '±0.001mm', layer: 'Blade Strain & Pyrometry Bus' },
    ],
  };
}
